_includes/head.html
HTTP from HTTPS problem regarding material icons.
=> Fixed HTTP from HTTPS problem

_includes/showcase_content.html
Removed a couple of newlines that were bugging me too.
=> Looked like too much of an ego booster, bringing myself back in line

_includes/side_nav.html, index.html
Join button now points to https://join.uqcs.org.au/.
=> Updated join button

_includes/showcase_content.html
removed http://inciteful.net and https://flappyarm.xyz fixes issue #89
=> Removed broken links 

_includes/showcase_content.html
I accidentally gave him the wrong title, so this is to correct that.
=> Improving grammer on the showcase page, and getting the title correct.

_includes/main_nav.html, _includes/side_nav.html
=> fixed hackathon links

_includes/main_nav.html
=> Fixed main nav hackathon link

_includes/head.html, _posts/2017-02-03-shirts-and-market-day.md, _posts/2017-04-07-python-library-talks.md, about.md, css/uqcs.css, index.html
Adding banner images to new posts is quite easy, just include it under the title.
Feedback appreciated as always :)
=> added banner images and improved article feed - fix #28 #58

config.toml, content/about/_index.html, layouts/partials/head.html, layouts/partials/hero.html, layouts/partials/nav.html, layouts/partials/sponsor-banner.html, static/css/uqcs.css
Fixes case where we use a non-root baseurl, like `http://uqcomputingsociety.github.io/website/`.
=> Fix Resource Linking

config.toml, layouts/_default/baseof.html, layouts/index.html, layouts/partials/nav/navbar-start.html, layouts/partials/scripts.html, static/js/navigation.js
=> Fix NavBar on Mobile

layouts/partials/nav/navbar-start.html, layouts/partials/share.html
Added youtube icon to both the top navbar and the share section of the website as per #159
=> Youtube icon

content/events/_index.html
Note that uses Google Calendar API so needs an API key ([documentation](https://fullcalendar.io/docs/google-calendar)). At the moment, it's using one of my keys and unrestricted. When merged, I'll limit the key to uqcs.org and uqcs.org.au.
=> Better events calendar using FullCalendar.js

content/events/_index.html
=> Responsive CSS for events calendar.

content/about/_index.html, content/constitution.html, layouts/partials/head.html
As per title. This takes the raw markdown file from UQCS' GitHub org and renders it. Same components can be used for #149. Preview:
=> Initialise constitution page

content/about/_index.html, content/code-of-conduct.html, content/constitution.html
Address #149 based on Madhav's work on #172.
=> Added Code of Conduct Page

layouts/_default/baseof.html, layouts/index.html, layouts/partials/firebase.html
=> Add firebase for analytics

README.md
please don't invalid my request, it's for a t-shirt :);
=> removed typo

content/competitions/hackathon-2020.html, content/showcase/_index.html
=>  Added rules, tweaked colour, reversed showcase.

README.md
=> Add steps for uploading to showcase

content/competitions/hackathon-2021.html
Hackathon is now at 49-301 for all the three days.
=> Remove mentions of 49-200.

content/talks/_index.html
Simple PR to add the 2022 talks playlist to the talks page
=> Add 2022 talks

content/competitions/hackathon-2023.html
Included the prizes page and a few minor updates
=> Updated hackathon page

static/hackathon_countdown.html
Adds gong, style changes and disables youtube video in back (stops accidental clicking)
=> Live Hackathoning website update

content/showcase/_index.html
Update the SuscatandStreet github link to its new location
=> Update SuscatandStreet github url

content/showcase/_index.html
Update the Elytra-Sniper github link to my new url
=> Update Elytra-Sniper github url
